apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: k3d-gateway-demo
servers: 1
agents: 2
options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: false # Enabled for proxying
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --disable=servicelb
        nodeFilters:
          - server:*
      - arg: --node-label=nodetype=front
        nodeFilters:
          - agent:0
      - arg: --node-label=nodetype=back
        nodeFilters:
          - agent:1
ports:
  # Map localhost:8081 to NodePort 30000 for HTTP
  - port: "8081:30000"
    nodeFilters:
      - loadbalancer
  # Map localhost:8443 to NodePort 30443 for HTTPS
  - port: "8443:30443"
    nodeFilters:
      - loadbalancer
