apiVersion: apps/v1
kind: Deployment
metadata:
  name: app001
  namespace: default
  labels:
    app: app001
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app001
  template:
    metadata:
      labels:
        app: app001
    spec:
      nodeSelector:
        nodetype: front
      containers:
        - name: nginx
          image: docker.io/library/nginx:alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: app001
  namespace: default
  labels:
    app: app001
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: app001
