apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: localhost-tls
  namespace: default
spec:
  dnsNames:
  - "*.localhost"
  - "rancher.localhost"
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-issuer
  secretName: localhost-tls
